### ISSUE TITLE
JPA Binding for JSR 354 (JavaMoney)

### ISSUE THREAD

**Issue by keilw** [soluvas/soluvas-framework#70]
Your Framework already got JScience/JSR 275 support for Hibernate which is great (also towards adding sometihing similar for JSR 275 replacement 363)

Have you thought about similar support for JavaMoney/JSR 354? 
http://javamoney.github.io/

**Comment by ceefour** [comment]
Sure in the future. However currently we're trying to align with Apache Tika/SIS for integrating with metadata and geo features, and it uses jsr275 instead of jscience which is even slightly incompatible.

Same for javamoney, we're now aligning with joda money first.

We still even haven't used java8's java.time because third party libs still use joda, so java9 techs are a bit future.

We're practically bound why whatever latest Tika & SIS happen to depend on.

**Comment by ceefour** [comment]
Why -> by

**Comment by ceefour** [comment]
BTW thanks for your care @keilw, this is such a small framework that only us use (despite open source) and you care to open a feature request :)

And don' take my comment before the wrong way, I truly deeply appreciate your dedication and hard work. But in our workflow it's easier to sync dependencies across projects and popular third party libs at once, reduces the chance of strange CNF, NPEs and whatnot.

**Comment by keilw** [comment]
Fyi, JSR 275 is exactly the same as JScience. GeoAPI contains a very recent 0.9.3 build of JSR 275, one of the last before it was rejected by JCP EC between 0.9.4 and 0.9.5. JScience may in some builds still be based on an older version, so with GeoAPI (0.9.3 or higher) dependencies you'd be safe for now. Note, JSR 275 according to JCP "does not exist" since it never went final. We're changing that with 363 based on a broader backing by industry players, including a 3rd Spec Lead with a strong foot in Embedded. If you wait till JSR 363 is final, sure no worries.
JSR 354 is final, and it outnumbers JodaMoney in download numbers and commercial use cases already;-) We took some very simple ideas or inspirations from it in the beginning, but found many of the shortcomings of JodaMoney (having to chose between 2 incompatible internal types BigMoney and Money for no reason, no solution for currency conversion) cumbersome. So did JUGs involved in the making (some tried to help JodaTime/JSR 310 but none of them seem to care about JodaMoney) getting JavaMoney to a good and stable 1.0 release.

**Comment by keilw** [comment]
See for yourself on JCenter: https://bintray.com/bintray/jcenter
While joda-time (fuelled by almost weekly TZ updates creating demand without any relevant API changes) is usually on the top page by "priority" which seems influenced by download stats, you'll find all JavaMoney (and also both JSR 275 and 363 slightly before;-) artifacts on the top 5 pages. Even JSR 354 Bitcoin support from the "Shelter" reached page 11. No sign of joda-money on the top 20 pages. Feel free to look for it (it's on JCenter, but like joda-time it does not share its real numbers, yet priority rank speaks for itself, it's pretty much irrelevant;-)

**Comment by ceefour** [comment]
Hey I didn't know that, thanks! Yes I think jodamoney is far below the popularity of jodatime. So you're saying JSR354 can already be used in java8 right? I guess it can be done then. Just need to find the time, though :D

Javatime and 363 is tricky since we use DateTime and Unit everywhere and they're not compatible, not even the interfaces. For javatime we'll wait until it got support from jackson & spring (boot, data, the whole shebang) arrives in spring 5... I hope you're not anti-spring :)

BTW have you talked with Tika/SIS/GeoAPI guys? Having your 363 in roadmap for their next (major) release will accelerate its adoption in so many other projects as well (including this one). I really hope you can persuade them. :)

**Comment by keilw** [comment]
http://mvnrepository.com/artifact/javax.money/money-api/usages shows, JSR 354 is supported by Spring Framework (who also signalled they would do) and a Jackson Binding by Zalando;-D
Moneta has 28 usages, including the same libraries or Jadira (somewhat competing with this framework I assume)

**Comment by ceefour** [comment]
Re: jadira, we don't compete with jadira, we use and extend jadira. Actually we proposed improved jadira implementations. Those not accepted (yet?) will live here first.

**Comment by ceefour** [comment]
You commented before on one of my tickets there hehe :) https://github.com/JadiraOrg/jadira/issues/15

**Comment by keilw** [comment]
Great, so you probably just get some of their Moneta support ;-)
While the current client has little use for currency conversion, the project here uses Jadira, too. Right now for Joda-Time, but with the upcoming JBoss EAP release we plan switching to JSR 310 inside Java 8. Potentially we could also use JSR 354 in areas where it makes sense for monetary types.

**Comment by ceefour** [comment]
@keilw Ironically, the popular JSR-354/JavaMoney articles/tutorials on the Internet are somewhat out-of-date. A quick "jsr-354 tutorial" googling gave me:

* http://www.slideshare.net/rajmahendra/jsr-354-money-and-currency-api
* http://www.javacodegeeks.com/2014/12/looking-into-the-java-9-money-and-currency-api-jsr-354.html
* http://www.infoq.com/articles/JSR-354-Java-Money-Currency-API

both of which gave me uncompilable code. `MonetaryCurrencies.getCurrency()` doesn't exist now, neither is `MoneyCurrency.of()`.

There should be updated articles/slides for these for v1.0 final ... and hopefully a "JodaMoney to JSR-354/JavaMoney Guide" as well.

Takes effort I know... :-)

**Comment by keilw** [comment]
They are always a child of their time;-)
Unfortunately unlike the community (e.g. Zalando created JSON binding, but using Jackson, not any JSON JSR, which is something the JCP and Oracle should worry about, we don't care what they use;-D) conferences like JavaOne ignore the topic. No proposal including one by last year's JCP Award winner and recent Java Champion @otaviojava were denied. So especially slides from major events come when there's demand for them. I just noticed because of a question on the mailing list, that a key element in Moneta 1 MonetaryUtils was deleted in the master. Something we have to fix. Even if a better or more advanced naming of some stuff might arise, backward compatibility has the highest priority;-) On another JSR 363 I was asked in a chat, why we did not use JSR 310 calling SECOND SECONDS, etc. That bug was introduced by folks like Doug Lea in an earlier JDK via java.util.concurrency.TimeUnit ;-) It is against SI standard naming or say Unicode CLDR also properly calling it SECOND, not SECONDS. However, the JDK neither renamed it nor offered a proper alternative, they just kept on with the "crap name". That often happens and nobody dares to fix it because too many apps use it already. We addressed e.g. a "factory creep" and consolidated several of them into *Monetary*. That's why you may see older documents refer to multiple of these classes.

HTH,
Werner

**Comment by ceefour** [comment]
@keilw CurrencyUnit "should" but not required to be `Serializable` :( too bad, it made things easier when in joda-money.

I guess in some places I'll just have to use `Money` instead, just to make (Wicket) APIs stop complaining about `CurrencyUnit` not `Serializable`... :(

**Comment by keilw** [comment]
I think that is especially to keep the core API as ME compliant as possible (Serializable does not exist in Java ME) and if you look at the "embryonal API" of `java.time`, the interface `TemporalAmount` does not extend `Serializable` either, but `Duration` then implements both it and `Comparable` or `Serializable`.

**Comment by ceefour** [comment]
@keilw Now this becomes a problem:

```
public abstract class AbstractSingleColumnUserType<T, J, C extends ColumnMapper<T, J>> extends AbstractUserType implements EnhancedUserType, Serializable {
```

:'(

Serializable !! ARGGGGGHHHHHH.....

**Comment by keilw** [comment]
Cool, thanks. We'll also try to document that at JavaMoney.org where we can in a "How To" section or similar ;-)
